### ISSUE TITLE
RFE: compile before running

### ISSUE THREAD

**Issue by jglick** [johnpoth/jshell-maven-plugin#11]
You get an error about a missing classpath entry if you try to run without first building the project. The workaround is to precede the mojo with, say, `test-compile`.

You already specify

```java
defaultPhase = LifecyclePhase.INSTALL
```

but this is ignored when you give a mojo rather than a phase on the CLI. It could probably just be dropped since it seems to have no effect.

Possibly it is necessary to just document how to get a similar effect by customizing your POM. Using the project from #10 as an example,

```diff
diff --git a/pom.xml a/pom.xml
index c8d4966..3a4acbe 100644
--- a/pom.xml
+++ a/pom.xml
@@ -32,4 +32,32 @@
             </plugin>
         </plugins>
     </build>
+    <profiles>
+        <profile>
+            <id>run</id>
+            <properties>
+                <skipTests>true</skipTests>
+            </properties>
+            <build>
+                <plugins>
+                    <plugin>
+                        <groupId>com.github.johnpoth</groupId>
+                        <artifactId>jshell-maven-plugin</artifactId>
+                        <version>1.4-SNAPSHOT</version>
+                        <executions>
+                            <execution>
+                                <phase>test</phase>
+                                <goals>
+                                    <goal>run</goal>
+                                </goals>
+                                <configuration>
+                                    <testClasspath>true</testClasspath>
+                                </configuration>
+                            </execution>
+                        </executions>
+                    </plugin>
+                </plugins>
+            </build>
+        </profile>
+    </profiles>
 </project>
```

lets

```bash
mvn -pl a -Prun
```

work (other than the lack of `target/classes`), even on a clean checkout. Alternately, for regular mode,

```diff
diff --git a/pom.xml a/pom.xml
index c8d4966..d78e348 100644
--- a/pom.xml
+++ a/pom.xml
@@ -32,4 +32,29 @@
             </plugin>
         </plugins>
     </build>
+    <profiles>
+        <profile>
+            <id>run</id>
+            <properties>
+                <skipTests>true</skipTests>
+            </properties>
+            <build>
+                <plugins>
+                    <plugin>
+                        <groupId>com.github.johnpoth</groupId>
+                        <artifactId>jshell-maven-plugin</artifactId>
+                        <version>1.4-SNAPSHOT</version>
+                        <executions>
+                            <execution>
+                                <phase>generate-test-sources</phase>
+                                <goals>
+                                    <goal>run</goal>
+                                </goals>
+                            </execution>
+                        </executions>
+                    </plugin>
+                </plugins>
+            </build>
+        </profile>
+    </profiles>
 </project>
```

Note that here I am specifying the [default phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference) immediately _after_ `process-classes` or `process-test-classes`, resp.; and need to `skipTests` to avoid wasting time on those (or add any other kind of unwanted slow verifications, like SpotBugs).

**Comment by johnpoth** [comment]
Hi @jglick, it's not very easy to properly build the project from a Maven plugin. Therefore I don't think I will include this logic into the jshell-maven-plugin.

I think it should be up to the user to properly build the project before invoke jshell-maven-plugin. I will update the README to run the plugin like so

`mvn compile com.github.johnpoth:jshell-maven-plugin:1.3:run`

Or use `test-compile` if test classes are needed or `install` for advanced use cases. I've added some logging to notify the user when the project wasn't built. WDYT ?

**Comment by jglick** [comment]
Sounds reasonable.

**Comment by jglick** [comment]
> it's not very easy to properly build the project from a Maven plugin

FYI, it is _possible_, using a forked execution.

**Comment by johnpoth** [comment]
For now, invoking the proper build phase will be the way to go, thanks @jglick for your feedback !
