### ISSUE TITLE
How to specify jshell command line options?

### ISSUE THREAD

**Issue by drightNo1** [johnpoth/jshell-maven-plugin#5]
Thank you for this useful utility.

Is there any way to add jshell command line options (https://docs.oracle.com/javase/9/tools/jshell.htm)? Or maybe include some of the jshell command line options in the plugin configration in the POM file? I wanted to specify a startup script for jshell, but I could not find a way to do so with this plugin.

Thanks!

**Comment by johnpoth** [comment]
Hi @drightNo1, thanks for the report! I'll try to add a fix for this ASAP.

**Comment by johnpoth** [comment]
Fixed in [1.2](https://github.com/johnpoth/jshell-maven-plugin/releases/tag/jshell-maven-plugin-1.2)

```
mvn com.github.johnpoth:jshell-maven-plugin:1.2:run -Djshell.scripts="script1,script2"
```

should do the trick.

**Comment by drightNo1** [comment]
Hi @johnpoth, thanks for the fix. Works like a charm!

**Comment by johnpoth** [comment]
Thank you @drightNo1 for the feedback!
