### ISSUE TITLE
How to run, given command just runs the build

### ISSUE THREAD

**Issue by sudipbhandari126** [johnpoth/jshell-maven-plugin#6]
I am not able to figure out how to run this.

`
mvn com.github.johnpoth:jshell-maven-plugin:1.1:run
[MVNVM] Using maven: 3.6.2
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 2 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 2 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Storage Parent                                                     [pom]
[INFO] Google Cloud Storage                                               [jar]
[INFO] 
[INFO] ------------< com.google.cloud:google-cloud-storage-parent >------------
[INFO] Building Storage Parent 1.105.0                                    [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- jshell-maven-plugin:1.1:run (default-cli) @ google-cloud-storage-parent ---
File '/Users/sudipbhandari/sudip/java-storage/target/classes' for '--class-path' is not found.
File '/Users/sudipbhandari/sudip/java-storage/target/classes' for '--class-path' is not found.
[INFO] 
[INFO] ---------------< com.google.cloud:google-cloud-storage >----------------
[INFO] Building Google Cloud Storage 1.105.0                              [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jshell-maven-plugin:1.1:run (default-cli) @ google-cloud-storage ---
File '/Users/sudipbhandari/sudip/java-storage/google-cloud-storage/target/classes' for '--class-path' is not found.
File '/Users/sudipbhandari/sudip/java-storage/google-cloud-storage/target/classes' for '--class-path' is not found.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Storage Parent 1.105.0:
[INFO] 
[INFO] Storage Parent ..................................... SUCCESS [  0.416 s]
[INFO] Google Cloud Storage ............................... SUCCESS [  0.344 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.494 s
[INFO] Finished at: 2020-03-06T12:16:14+05:30
[INFO] ------------------------------------------------------------------------
`

**Comment by johnpoth** [comment]
Hi @sudipbhandari126,

Can you run a `mvn clean install` first and then try? Thanks !

**Comment by sudipbhandari126** [comment]
Yes.  It worked
Thanks!!!
